import { mkdir, copyFile, readFile, writeFile, rm } from "node:fs/promises";
import path from "node:path";

const root = process.cwd();
const srcDir = path.join(root, "src");
const webSrcDir = path.join(srcDir, "web");
const webDistDir = path.join(root, "dist", "web");
const entrypoint = path.join(srcDir, "entrypoints", "web_entrypoint.rb");
const staticFiles = [
  "index.html",
  "mobile_index.html",
  "pc_index.html",
  "ruby_wasm_boot.js"
];

const seen = new Set();
const requireRelativePattern = /^\s*require_relative\s+["']([^"']+)["']/gm;

const rubyPath = (fromFile, relativePath) => {
  const withExtension = path.extname(relativePath) ? relativePath : `${relativePath}.rb`;
  return path.normalize(path.resolve(path.dirname(fromFile), withExtension));
};

const dependenciesFor = (file, source) => {
  const dependencies = [];
  for (const match of source.matchAll(requireRelativePattern)) {
    dependencies.push(rubyPath(file, match[1]));
  }
  return dependencies;
};

const stripRequireRelative = (source) => (
  source
    .split("\n")
    .filter((line) => !line.trimStart().startsWith("require_relative "))
    .join("\n")
);

const bundle = async (file) => {
  const normalizedFile = path.normalize(file);
  if (seen.has(normalizedFile)) {
    return "";
  }

  seen.add(normalizedFile);
  const source = await readFile(normalizedFile, "utf8");
  const dependencies = dependenciesFor(normalizedFile, source);
  const bundledDependencies = [];
  for (const dependency of dependencies) {
    bundledDependencies.push(await bundle(dependency));
  }
  const relativeName = path.relative(root, normalizedFile);
  const strippedSource = stripRequireRelative(source).trimEnd();

  return [
    ...bundledDependencies,
    `# ${relativeName}`,
    strippedSource,
    ""
  ].join("\n");
};

await rm(webDistDir, { recursive: true, force: true });
await mkdir(webDistDir, { recursive: true });

await Promise.all(staticFiles.map((file) => (
  copyFile(path.join(webSrcDir, file), path.join(webDistDir, file))
)));

const appSource = await bundle(entrypoint);
await writeFile(
  path.join(webDistDir, "app.rb"),
  `# frozen_string_literal: true\n# Generated by scripts/build_web.mjs. Do not edit.\n\n${appSource}`,
  "utf8"
);
